name: llm-ms4m
#Cuando ejecutas mamba env create -f environment.yml:
#Buscará cada paquete primero en pytorch
#Si no lo encuentra, buscará en conda-forge
#Finalmente buscará en defaults
channels:
  - pytorch  # ¡IMPORTANTE! Este canal debe ir primero
  - conda-forge
  - defaults
dependencies:
  # Paquetes base esenciales
  - python=3.10.12
  - numpy=1.26.4
  - pip
  - mamba
  - conda-pack=0.7.0

  # Machine Learning y Procesamiento
  - pytorch=2.1.0  # Versión estable y compatible
  - torchvision=0.16.0
  - torchaudio=2.1.0
  
  #- cudatoolkit=12.1  # Solo para GPU
  - scipy=1.13.0
  - scikit-learn=1.4.0
  - transformers=4.37.0
  - sentence-transformers=2.7.0
  #- onnxruntime=1.21.0   # Sin GPU 
  - tiktoken=0.9.0
  - tokenizers=0.15.2
  #- tokenizers=0.21.0
  

  # Procesamiento de Datos
  - pandas=2.1.4
  - openpyxl=3.1.2
  - lxml=5.3.1
  - beautifulsoup4=4.13.3
  - pypdf=5.3.1
  - python-docx=1.1.2
  - python-pptx=1.0.2

  # Paquetes via pip (organizados por categoría)
  - pip:
    # Framework LLM
    - langchain==0.3.20
    - langchain-community==0.3.19
    - langchain-core==0.3.41
    - chromadb==0.6.3
    - chroma-hnswlib==0.7.6
    - accelerate==1.4.0
    - bitsandbytes==0.45.3
    - unstructured==0.17.0
    - langchain-huggingface==0.1.2
    
    # Backend/API
    - fastapi==0.115.11
    - uvicorn==0.34.0
    - starlette==0.46.1
    - pydantic==2.10.6
    - sqlalchemy==2.0.38
    - psycopg2-binary==2.9.10
    - markdownify==1.1.0
    
    # Async/Networking
    - aiohttp==3.11.13
    - aiofiles==24.1.0
    - httpx==0.28.1
    - requests==2.32.3
    - websockets==15.0.1
    
    # Seguridad y Autenticación
    - google-auth==2.38.0
    - cryptography==44.0.2
    - bcrypt==4.3.0
    - rsa==4.9
    
    # Utilidades
    - python-dotenv==1.0.1
    - rich==13.9.4
    - tqdm==4.67.1
    - tenacity==9.0.0
    - protobuf>=4.21.6,<7.0.0
    - packaging==24.2
    - pypandoc==1.15
    - atlassian-python-api==4.0.3
    
    # Monitorización y Logging
    - opentelemetry-api==1.31.0
    - opentelemetry-sdk==1.31.0
    - coloredlogs==15.0.1
    
    # Windows-specific (solo se instalará en Windows)
    - pywin32==308; sys_platform == 'win32'